In [2]:
import plotly.offline as pyo
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot
import pandas as pd
init_notebook_mode(connected=True)
import cufflinks as cf
cf.go_offline()
import plotly.graph_objects as go
import numpy as np
from plotly import subplots

In [3]:
df = pd.read_csv('OECDBLI2017.csv')
df.head()

,Country,Dwellings without basic facilities as pct,Housing expenditure as pct,Rooms per person as rat,Household net adjusted disposable income in usd,Household net financial wealth in usd,Labour market insecurity as pct,Employment rate as pct,Long-term unemployment rate as pct,Personal earnings in usd,...,Water quality as pct,Stakeholder engagement for developing regulations as avg score,Voter turnout as pct,Life expectancy in yrs,Self-reported health as pct,Life satisfaction as avg score,Feeling safe walking alone at night as pct,Homicide rate as rat,Employees working very long hours as pct,Time devoted to leisure and personal care in hrs
0,Australia,1.1,20,2.3,33417,57462,4.3,72,1.36,52063,...,92,2.7,91,82.5,85,7.3,63.6,1.0,13.20,14.35
1,Austria,1.0,21,1.6,32544,59574,2.7,72,1.94,48295,...,93,1.3,75,81.3,70,7.0,80.7,0.4,6.78,14.55
2,Belgium,2.3,21,2.2,29968,104084,4.8,62,3.98,49587,...,84,2.2,89,81.1,75,6.9,70.7,1.0,4.31,15.77
3,Canada,0.2,22,2.5,29850,85758,3.9,73,0.81,48403,...,91,3.0,68,81.5,88,7.3,80.9,1.4,3.73,14.41
4,Chile,9.4,18,1.9,16588,21409,8.1,62,2.02,28434,...,69,1.5,49,79.1,57,6.7,51.1,4.5,10.06,14.90

In [4]:
df.set_index('Country')['Employment rate as pct'].sort_values(ascending=False).iplot(kind='bar')

In [5]:
df.iplot(kind='scatter',
x='Labour market insecurity as pct',
y='Employment rate as pct',
mode='markers',
         	xTitle='Labour market insecurity as pct',
yTitle='Employment rate as pct',
text='Country')

In [6]:
df['Water quality as pct'].iplot(kind='hist')

In [7]:
df.iplot(kind='bubble',
         x='Air pollution in ugm3',
         y='Water quality as pct',
         size='Household net financial wealth in usd',
        title='Zanieczyszczenie powietrza oraz jakość wody w porównaniu do zamożności gospodarstwa domowego',
        text='Country')

In [8]:
df2 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})
df2.iplot(kind='surface',colorscale='rdylbu')

In [9]:
trace0 = go.Scatter(x=df['Labour market insecurity as pct'],
                   y=df['Employment rate as pct'],
                   mode='markers',
                   marker=dict(
                           size=15,
                           color='rgb(10, 166, 106)'),
                  text=df['Country'])
data = [trace0]
layout = go.Layout(title='Labour market insecurity vs Employment rate',
                  xaxis=dict(title='Labour market insecurity'),
                  yaxis=dict(title='Employment rate'),
                  hovermode='closest')
iplot(go.Figure(data= data,layout=layout))

In [10]:
x = np.arange(1900,2021)
y = np.random.randint(1000,2000,len(x))
y2 = np.random.randint(500,1000,len(x))
fig = go.Figure()
fig.add_trace(go.Scatter(x=x,y=y,name='y line'))
fig.add_trace(go.Scatter(x=x,y=y2,name='y2 markers',mode='markers'))
fig.update_layout(title='y vs y2')
iplot(fig)

In [11]:
fig = go.Figure()

data = df.sort_values(by='Employment rate as pct',ascending=False)

fig.add_trace(go.Bar(x=data['Country'],y=data['Employment rate as pct']))

fig.update_layout(title='Employment rate as pct')

iplot(fig)

In [12]:
fig = go.Figure()

colors = ['lightslategray',] * len(data)
colors[data['Country'].tolist().index('OECD - Total')] = 'crimson'
data = df.sort_values(by='Employment rate as pct',ascending=False)

fig.add_trace(go.Bar(x=data['Country'],y=data['Employment rate as pct'],marker_color=colors))
fig.update_layout(title='Employment rate as pct')

iplot(fig)

In [13]:
fig = go.Figure()

data = df.sort_values(by='Employment rate as pct',ascending=False)

fig.add_trace(go.Bar(x=data['Country'],y=data['Employment rate as pct'],name='Employment rate'))

fig.add_trace(go.Bar(x=data['Country'],y=data['Self-reported health as pct'],name='Self-reported health'))
iplot(fig)

In [14]:
cn = pd.read_csv('countrynames.csv')
cn.head()
df['Region'] = df['Country'].map(cn.set_index('name')['region'])
colors = df['Region'].map(dict(zip(df['Region'].unique(),['Green','Blue','Red','Yellow','Gray','Black'])))
fig = go.Figure()

fig.add_trace(go.Scatter(x=df['Air pollution in ugm3'],
                        y=df['Water quality as pct'],
                        text=df['Country'],
                        mode='markers',
                        marker=dict(size=df['Household net financial wealth in usd']/2000,
                                   color=colors)))
fig.update_layout(title='Zanieczyszczenie powietrza oraz jakość wody w porównaniu do zamożności gospodarstwa domowego',
                 xaxis=dict(title='Air pollution in ugm3'),
                 yaxis=dict(title='Water quality as pct'))

iplot(fig)

In [15]:
wro_temp = pd.read_csv('dataexport_20200613T163949.csv',skiprows=9,index_col=0,parse_dates=True)
wro_temp.head()

,Wrocław Temperature [2 m elevation corrected],Wrocław Precipitation Total,Wrocław Wind Speed [10 m],Wrocław Wind Direction [10 m]
timestamp,,,,
2020-06-01 00:00:00,13.444630,0.0,11.038736,8.325638
2020-06-01 01:00:00,12.224629,0.0,10.738927,7.125000
2020-06-01 02:00:00,11.424629,0.0,10.922400,12.680374
2020-06-01 03:00:00,10.614630,0.0,10.084568,12.200455
2020-06-01 04:00:00,9.784630,0.0,9.155017,8.365875

In [16]:
fig = go.Figure()

fig.add_trace(go.Heatmap(x=wro_temp.index.hour,
                         y=wro_temp.index.weekday.map({0:'Poniedziałek',1:'Wtorek',2:'Środa',
                                                       3:'Czwartek',4:'Piątek',5:'Sobota',6:'Niedziela'}),
                         z=wro_temp['Wrocław Temperature [2 m elevation corrected]'].tolist()))
fig.update_layout(title='Temperatura we Wrocławiu w pierwszym tyg. czerwca')
iplot(fig)

In [19]:
fig = subplots.make_subplots(rows=1,cols=2,subplot_titles=['Temperatura','Opady'],shared_yaxes=True)
fig.add_trace(go.Heatmap(x=wro_temp.index.hour,
                         y=wro_temp.index.weekday.map({0:'Poniedziałek',1:'Wtorek',2:'Środa',3:'Czwartek',4:'Piątek',5:'Sobota',6:'Niedziela'}),
                         z=wro_temp['Wrocław Temperature [2 m elevation corrected]'].tolist(),
                        colorscale='Jet',
                        showscale=False),1,1)

fig.add_trace(go.Heatmap(x=wro_temp.index.hour,
                         y=wro_temp.index.weekday.map({0:'Poniedziałek',1:'Wtorek',2:'Środa',3:'Czwartek',4:'Piątek',5:'Sobota',6:'Niedziela'}),
                         z=wro_temp['Wrocław Precipitation Total'].tolist(),
                        colorscale='Cividis',
                        showscale=False),1,2)
fig.update_layout(title='Pogoda we Wrocławiu w pierwszym tyg. czerwca')
iplot(fig)